name: schhs_app2021
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.12
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  google_maps_flutter: ^2.1.0
  bottom_navy_bar: ^6.0.0
  http: ^0.13.4
  new_gradient_app_bar: ^0.2.0
  flutter_form_builder: ^7.0.0
  sqflite: ^2.0.0+4
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.1
  image_picker: ^0.8.4+4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  expansion_tile_card: ^2.0.0
  font_awesome_flutter: ^9.2.0
  table_calendar: ^3.0.3
  shared_preferences: ^2.0.8
  webview_flutter: ^2.3.0
  animated_splash_screen: ^1.1.0
  splash_screen_view: ^3.0.0
  flutter_launcher_icons: ^0.9.2
  qr_flutter: ^4.0.0


  barcode_scan2:
  flutter_barcode_scanner: ^2.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  get: ^4.3.8
  path:
  maps_launcher: ^2.0.1
  vertical_card_pager: ^1.5.0
  pinch_zoom: ^1.0.0
dev_dependencies:

  flutter_test:
    sdk: flutter

  # hive database
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # hive database generators
  build_runner: ^2.1.5
  hive_generator: ^1.1.1

  flutter_launcher_icons: ^0.9.2


# The following section is specific to Flutter.
flutter_icons:
  image_path: "assets/icons/circles2.png"
  android: true
  ios: true


flutter:
  assets:
    - assets/images/
    - assets/txtFiles/
    - json/

  fonts:
    - family: Meta
      fonts:
        - asset: assets/fonts/MtBdLFRo.ttf
       # - asset: assets/fonts/MtBkLFIt.ttf
        - asset: assets/fonts/MtBkLFRo.ttf
       # - asset: assets/fonts/MtMeRF_.ttf

  uses-material-design: true


splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.

  color: "#ffffff"
  #background_image: "assets/splashscreen_image.png"

  # Optional parameters are listed below.
  image: assets/images/SCHHS_black.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  #android: false
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  #fullscreen: true

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
